### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by bilibili-bidge** [haoming37/TheOtherRoles-GM-Haoming#52]
I have a question, I am a Chinese and I want to sinicize your Mod, I found the Python source file in TheOtherRoles-GM-Haoming. The error I encountered during compilation is about this file, do you know how to fix it?

問題があります。私は中国人です。あなたのModを中国化したいです。theotherroles-gm-haomingでPythonのソースファイルを見つけました。私がコンパイルの過程で遭遇したエラーはこのファイルに関するもので、あなたはそれを修復する方法を知っていますか?

**Comment by haoming37** [comment]
To resolve this problem, install python and openpyxl by pip command

1. get latest python from below
https://www.python.org/downloads/
2. install python
3. add python path to environment variable
4. launch command below
```
$ py -m pip install openpyxl
```

**Comment by bilibili-bidge** [comment]
I saw an article in China, which said: using Python in c#, you can compile the source code of Python into executable files (exe)
Do I want to compile this Python file into exe? If so, how should I change the code
